on:
  push:
    branches:
      - main
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - run: npm test
      - name: Collect coverage from client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
      - name: Collect coverage from server
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}